// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCHszGq7GhQq_Cb3H-o4fEUO3jWuCHHw',
    appId: '1:159443933809:web:fb8f9bc3389cd27beb99d0',
    messagingSenderId: '159443933809',
    projectId: 'safe-connect-app-1',
    authDomain: 'safe-connect-app-1.firebaseapp.com',
    databaseURL: 'https://safe-connect-app-1-default-rtdb.firebaseio.com',
    storageBucket: 'safe-connect-app-1.appspot.com',
    measurementId: 'G-2T5ZG30ZYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjf31wGfi-tzT1gnuLxzeLi8OhSxpfqnc',
    appId: '1:159443933809:android:196f5b9e4bb54d63eb99d0',
    messagingSenderId: '159443933809',
    projectId: 'safe-connect-app-1',
    databaseURL: 'https://safe-connect-app-1-default-rtdb.firebaseio.com',
    storageBucket: 'safe-connect-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETcdx4-5EWSKhDeoJBijV4zdHPESwn0Y',
    appId: '1:159443933809:ios:7a78791265b3308eeb99d0',
    messagingSenderId: '159443933809',
    projectId: 'safe-connect-app-1',
    databaseURL: 'https://safe-connect-app-1-default-rtdb.firebaseio.com',
    storageBucket: 'safe-connect-app-1.appspot.com',
    androidClientId: '159443933809-hc1t91i3pvgol73nlnkte2j09ium3jab.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeConnect',
  );
}
